from __future__ import annotations

from typing import Any, Dict, List, Mapping, Optional, Protocol, Sequence


class KnowledgeRepositoryPort(Protocol):
    def list_kbs(self) -> Sequence[Any]: ...

    def get_kb(self, kb_id: int) -> Optional[Any]: ...

    def create_kb(self, payload: Any) -> Any: ...

    def update_kb(self, kb_id: int, patch: Any) -> Any: ...

    def delete_kb(self, kb_id: int) -> None: ...

    def list_files(self, kb_id: int) -> Sequence[Any]: ...

    def get_file(self, kb_id: int, file_id: int) -> Optional[Any]: ...

    def create_file(self, kb_id: int, payload: Any) -> Any: ...

    def update_file(self, kb_id: int, file_id: int, patch: Any) -> Any: ...

    def delete_file(self, kb_id: int, file_id: int) -> None: ...

    def list_chunks(self, kb_id: int, file_id: int) -> Sequence[Any]: ...


class KnowledgeBaseControllerPort(Protocol):
    base_dir: str

    def kb_dir(self, kb_id: int) -> str: ...

    def ensure_kb(self, kb_id: int) -> None: ...

    def createKnowledgeBase(self, kb_id: int, *, reset_sqlite: bool = True) -> None: ...

    def deleteKnowledgeBase(self, kb_id: int) -> None: ...

    def deleteFile(self, kb_id: int, file_id: int) -> bool: ...


class KbFileStoragePort(Protocol):
    def ensure_uploads_dir(self, kb_id: int) -> str: ...

    def upload_path(self, kb_id: int, filename: str) -> str: ...

    def write_bytes(self, path: str, data: bytes) -> None: ...

    def exists(self, path: str) -> bool: ...

    def list_kb_ids(self, base_dir: str) -> List[int]: ...

    def kb_created_at_ms(self, kb_dir: str) -> int: ...


class KnowledgeFileResolverPort(Protocol):
    def find_file_id_by_name(self, kb_id: int, filename: str) -> int: ...


class AssetPathProviderPort(Protocol):
    def assets_images_dir(self, kb_id: int, file_id: int) -> str: ...


class KnowledgeChunkWriterPort(Protocol):
    def save_chunks(self, kb_id: int, file_id: int, chunks: List[Any]) -> None: ...


class PdfMarkdownExtractorPort(Protocol):
    def extract_markdown(self, pdf_path: str, image_dir: str) -> str: ...


class ImageCaptionerPort(Protocol):
    def caption(self, jobs: List[Dict[str, Any]], *, batch_size: int, max_images: int) -> Mapping[int, str]: ...


class ExcelTextExtractorPort(Protocol):
    def extract_text(self, excel_path: str, *, max_rows_per_sheet: int, max_cols: int) -> str: ...


class TableChunkerPort(Protocol):
    def split_table(
        self,
        *,
        text: str,
        kb_id: int,
        file_id: int,
        table_name: str,
        use_llm_summary: bool,
        max_rows_per_chunk: int,
        max_chars_per_chunk: int,
    ) -> List[Any]: ...
