CONFIG_KEY_LLM_BASE_URL = "llm.baseUrl"
CONFIG_KEY_LLM_MODEL = "llm.model"
CONFIG_KEY_LLM_API_KEY = "llm.apiKey"

CONFIG_KEY_EMBEDDING_BASE_URL = "embedding.baseUrl"
CONFIG_KEY_EMBEDDING_MODEL = "embedding.model"
CONFIG_KEY_EMBEDDING_API_KEY = "embedding.apiKey"

CONFIG_KEY_RERANKER_BASE_URL = "reranker.baseUrl"
CONFIG_KEY_RERANKER_MODEL = "reranker.model"
CONFIG_KEY_RERANKER_API_KEY = "reranker.apiKey"
CONFIG_KEY_RERANKER_PRE_K = "reranker.preK"

CONFIG_KEY_VLL_BASE_URL = "vll.baseUrl"
CONFIG_KEY_VLL_MODEL = "vll.model"
CONFIG_KEY_VLL_API_KEY = "vll.apiKey"

# Logging related unified keys
CONFIG_KEY_LOG_DIR = "log.dir"
CONFIG_KEY_LOG_FILE = "log.file"
CONFIG_KEY_LOG_LEVEL = "log.level"
CONFIG_KEY_LOG_TO_CONSOLE = "log.toConsole"
CONFIG_KEY_LOG_MAX_BYTES = "log.maxBytes"
CONFIG_KEY_LOG_BACKUP_COUNT = "log.backupCount"

ENV_LLM_BASE_URL = "LLM_BASE_URL"
ENV_LLM_MODEL = "LLM_MODEL"
ENV_LLM_API_KEY = "LLM_API_KEY"
ENV_DEEPSEEK_API_KEY = "DEEPSEEK_API_KEY"

ENV_EMBEDDING_BASE_URL = "EMBEDDING_BASE_URL"
ENV_EMBEDDING_MODEL = "EMBEDDING_MODEL"
ENV_EMBEDDING_API_KEY = "EMBEDDING_API_KEY"

ENV_RERANKER_BASE_URL = "RERANKER_BASE_URL"
ENV_RERANKER_MODEL = "RERANKER_MODEL"
ENV_RERANKER_API_KEY = "RERANKER_API_KEY"
ENV_RERANKER_PRE_K = "RERANKER_PRE_K"

ENV_VLL_BASE_URL = "VLL_BASE_URL"
ENV_VLL_MODEL = "VLL_MODEL"
ENV_VLL_API_KEY = "VLL_API_KEY"

# Logging related env names
ENV_LOG_DIR = "LOG_DIR"
ENV_LOG_FILE = "LOG_FILE"
ENV_LOG_LEVEL = "LOG_LEVEL"
ENV_LOG_TO_CONSOLE = "LOG_TO_CONSOLE"
ENV_LOG_MAX_BYTES = "LOG_MAX_BYTES"
ENV_LOG_BACKUP_COUNT = "LOG_BACKUP_COUNT"

ENV_TO_CONFIG_MAP = {
    ENV_LLM_BASE_URL: CONFIG_KEY_LLM_BASE_URL,
    ENV_LLM_MODEL: CONFIG_KEY_LLM_MODEL,
    ENV_LLM_API_KEY: CONFIG_KEY_LLM_API_KEY,
    ENV_EMBEDDING_BASE_URL: CONFIG_KEY_EMBEDDING_BASE_URL,
    ENV_EMBEDDING_MODEL: CONFIG_KEY_EMBEDDING_MODEL,
    ENV_EMBEDDING_API_KEY: CONFIG_KEY_EMBEDDING_API_KEY,
    ENV_RERANKER_BASE_URL: CONFIG_KEY_RERANKER_BASE_URL,
    ENV_RERANKER_MODEL: CONFIG_KEY_RERANKER_MODEL,
    ENV_RERANKER_API_KEY: CONFIG_KEY_RERANKER_API_KEY,
    ENV_RERANKER_PRE_K: CONFIG_KEY_RERANKER_PRE_K,
    ENV_VLL_BASE_URL: CONFIG_KEY_VLL_BASE_URL,
    ENV_VLL_MODEL: CONFIG_KEY_VLL_MODEL,
    ENV_VLL_API_KEY: CONFIG_KEY_VLL_API_KEY,
    ENV_LOG_DIR: CONFIG_KEY_LOG_DIR,
    ENV_LOG_FILE: CONFIG_KEY_LOG_FILE,
    ENV_LOG_LEVEL: CONFIG_KEY_LOG_LEVEL,
    ENV_LOG_TO_CONSOLE: CONFIG_KEY_LOG_TO_CONSOLE,
    ENV_LOG_MAX_BYTES: CONFIG_KEY_LOG_MAX_BYTES,
    ENV_LOG_BACKUP_COUNT: CONFIG_KEY_LOG_BACKUP_COUNT,
}
