from __future__ import annotations

from typing import Any, Dict, List, Mapping, Optional, Protocol, Sequence

from .chunk_models import DocumentChunk
from .enums import PdfDocumentType


class KnowledgeRepositoryPort(Protocol):
    def list_kbs(self) -> Sequence[Any]: ...

    def get_kb(self, kb_id: int) -> Optional[Any]: ...

    def create_kb(self, payload: Any) -> Any: ...

    def update_kb(self, kb_id: int, patch: Any) -> Any: ...

    def delete_kb(self, kb_id: int) -> None: ...

    def list_documents(self, kb_id: int) -> Sequence[Any]: ...

    def get_document(self, kb_id: int, document_id: int) -> Optional[Any]: ...

    def create_document(self, kb_id: int, payload: Any) -> Any: ...

    def update_document(self, kb_id: int, document_id: int, document: Any) -> Any: ...

    def delete_document(self, kb_id: int, document_id: int) -> None: ...

    def list_document_chunks(self, kb_id: int, document_id: int) -> Sequence[Any]: ...

    def upsert_document_chunks(self, kb_id: int, document_id: int, chunks: List[Any]) -> None: ...

    def delete_document_chunks(self, kb_id: int, document_id: int) -> None: ...


class KnowledgeBaseControllerPort(Protocol):
    base_dir: str

    def kb_dir(self, kb_id: int) -> str: ...

    def ensure_kb(self, kb_id: int) -> None: ...

    def createKnowledgeBase(self, kb_id: int, *, reset_sqlite: bool = True) -> None: ...

    def deleteKnowledgeBase(self, kb_id: int) -> None: ...

    def deleteDocument(self, kb_id: int, document_id: int) -> bool: ...


class KbDocumentStoragePort(Protocol):
    def ensure_uploads_dir(self, kb_id: int) -> str: ...

    def upload_path(self, kb_id: int, filename: str) -> str: ...

    def write_bytes(self, path: str, data: bytes) -> None: ...

    def exists(self, path: str) -> bool: ...

    def list_kb_ids(self, base_dir: str) -> List[int]: ...

    def kb_created_at_ms(self, kb_dir: str) -> int: ...


class KnowledgeDocumentResolverPort(Protocol):
    def find_document_id_by_name(self, kb_id: int, filename: str) -> int: ...


class AssetPathProviderPort(Protocol):
    def assets_images_dir(self, kb_id: int, document_id: int) -> str: ...


class KnowledgeChunkWriterPort(Protocol):
    def save_document_chunks(self, kb_id: int, document_id: int, chunks: List[Any]) -> bool: ...


class PdfMarkdownExtractorPort(Protocol):
    def extract(self, pdf_path: str, image_dir: str, document_type: PdfDocumentType) -> tuple[str, List[DocumentChunk]]: ...


class ImageCaptionerPort(Protocol):
    def caption(
        self,
        chunks: Sequence[DocumentChunk],
        *,
        batch_size: int = 1,
        max_images: Optional[int] = None,
    ) -> List[DocumentChunk]: ...


class ExcelTextExtractorPort(Protocol):
    def extract_text(self, excel_path: str, *, max_rows_per_sheet: int, max_cols: int) -> str: ...


class TableChunkerPort(Protocol):
    def split_table(
        self,
        *,
        text: str,
        kb_id: int,
        document_id: int,
        table_name: str,
        use_llm_summary: bool,
        max_rows_per_chunk: int,
        max_chars_per_chunk: int,
    ) -> List[Any]: ...


class TextSplitterPort(Protocol):
    def split(self, text: str, kb_id: int, document_id: int) -> List[Any]: ...


class VectorStorePort(Protocol):
    def add(self, kb_id: int, chunks: List[Any]) -> None: ...

    def search(self, kb_id: int, query: str, top_k: int) -> List[Any]: ...

    def delete_by_filter(self, kb_id: int, filters: Dict[str, Any]) -> None: ...

    def clear(self, kb_id: int) -> None: ...


class EmbeddingPort(Protocol):
    def embed_texts(self, texts: List[str]) -> List[Any]: ...


class RerankPort(Protocol):
    def rerank(self, query: str, documents: List[str], top_k: int) -> List[int]: ...


class SearchPort(Protocol):
    def search(self, kb_id: int, query: str, top_k: int) -> List[Any]: ...

    def get_documents_meta(self, kb_id: int, document_ids: List[int]) -> List[Any]: ...

    def read_document_chunks(self, kb_id: int, chunks: List[Dict[str, int]]) -> List[Any]: ...

    def list_documents_paginated(self, kb_id: int, page: int, page_size: int) -> List[Any]: ...
